---
version: 2
updates:
  - assignees:
      - "kampfmoehre"
    commit-message:
      prefix: "chore"
    groups:
      ef-core:
        patterns:
          - "Microsoft.EntityFrameworkCore"
          - "Microsoft.EntityFrameworkCore.*"
      roslynator:
        patterns:
          - "Roslynator.*"
      xunit:
        patterns:
          - "xunit"
          - "xunit.*"
    directory: /
    open-pull-requests-limit: 10
    package-ecosystem: nuget
    rebase-strategy: auto
    schedule:
      interval: daily
  - assignees:
      - "kampfmoehre"
    commit-message:
      prefix: "ci"
    directory: /
    groups:
      commitlint:
        patterns:
          - "@commitlint/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
    open-pull-requests-limit: 10
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: daily
  - assignees:
      - "kampfmoehre"
    commit-message:
      prefix: "ci"
    directory: /
    open-pull-requests-limit: 10
    package-ecosystem: github-actions
    rebase-strategy: auto
    schedule:
      interval: daily
